### ISSUE TITLE
FPS

### ISSUE THREAD

**Issue by TheFlatStanley** [TechHog8984/droppher#2]
I was playing the game (Minecraft) on the Hypixel server, when I noticed that my frames per second (FPS if you will) was around 500 (this will be relevant later). I decided to queue up some games of my favorite Hypixel Minigame: Dropper. Upon losing game after game I decided to download your overlay. As I started to use it, I noted that my FPS was still around 500. This made me very upset, as I was looking forward to the FPS boost that the overlay would give me. I am writing this response to inform you that your overlay is a scam, as it did NOTHING to boost my FPS. I am very unsatisfied and I will now be using DroppHim instead as it BOOSTS my FPS :). 
 Best Wishes - duhh

**Comment by TechHog8984** [comment]
For legal reasons this is a joke.
